### ISSUE TITLE
最近遇到一件安装脚本启动失败的情况，base 基础库获取失败！

### ISSUE THREAD

**Issue by voidzi** [xiaoyaDev/xiaoya-alist#240]
几个都尝试了一下，提示均显示如下：
bash -c "$(curl --insecure -fsSL https://ddsrem.com/xiaoya_install.sh)"
[INFO] 脚本获取成功！
[INFO] 初始化中，请稍等....
curl: (35) OpenSSL SSL_connect: SSL_ERROR_SYSCALL in connection to gitee.com:443
[ERROR] base 基础库获取失败！
[ERROR] 请检查是否能访问 gitee.com！

但是ping gitee.com是有回复的。
昨天和前天第一次运行都可以，解压了一下元数据后，再运行安装脚本就一直提示base基础库获取失败。

直接Git clone到本地运行，base基础库倒是加载成功了，但是又提示image_mirror 基础库获取失败！

ping gitee.com
PING gitee.com-31ba39d0fd3.baiduads.com (180.76.198.225) 56(84) bytes of data.
64 bytes from 180.76.198.225 (180.76.198.225): icmp_seq=1 ttl=55 time=34.4 ms
64 bytes from 180.76.198.225 (180.76.198.225): icmp_seq=2 ttl=55 time=34.5 ms
64 bytes from 180.76.198.225 (180.76.198.225): icmp_seq=3 ttl=55 time=34.4 ms
...中略
--- gitee.com-31ba39d0fd3.baiduads.com ping statistics ---
8 packets transmitted, 8 received, 0% packet loss, time 45670ms
rtt min/avg/max/mdev = 34.331/34.578/34.937/0.187 ms

**Comment by systemoutprintlnhelloworld** [comment]
+1，我也是这个情况，怎么issue还关了

**Comment by W-KE** [comment]
Forbidden
Request forbidden by administrative rules.(code:20005-10-31.13)

应该是gitee屏蔽国外ip，gitee的任何页面都打不开

**Comment by DDSDerek** [comment]
脚本已经更新，已支持从github拉取
